In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [186]:
data = pd.read_csv('wall-robot-nav.csv').sample(frac=1)
X = data.loc[:, 'V1':'V24']
X = X / np.array(X).max(axis=0)
y = data['Class']
train_size = math.ceil(X.shape[0]*0.75)
test_size = X.shape[0] - train_size
X_train = X.head(train_size)
y_train = y.head(train_size)
X_test = X.tail(test_size)
y_test = y.tail(test_size)

In [187]:

def distance_euclid(x, xi):
    return np.sqrt((np.square(x-xi)).sum(axis=1))


def uniform_kernel(x):
    new_x = x
    new_x[new_x<=1] = 0.5
    new_x[new_x>1] = 0
    return new_x

class KernelRegressionClassifier:

    distance_functions = {
        'euclid': distance_euclid
    }

    kernels = {
        'uniform': uniform_kernel,
    }

    def __init__(self, X, y, h, k=10, kernel_name='uniform', distance_func_name='euclid'):
        self.k = k
        self.h = h
        self.kernel_name = kernel_name
        self.distance_func_name = distance_func_name
        self.X = X
        self.y = y
        self.kernel = self.kernels[self.kernel_name]
        self.distance_func = self.distance_functions[self.distance_func_name]

    def predict(self, x):
        x = x
        X_distance = np.apply_along_axis(self.distance_func, 1, x, self.X)
        print(X_distance)
        X_smoothed = self.kernel(X_distance/self.h)
        result = []
        for row in X_smoothed:
            # alg = (row[is_close_enough] * self.y[is_close_enough]).sum() / (row[is_close_enough].sum() or 1)
            # result.append(math.ceil(alg))
        return result

In [188]:
clf = KernelRegressionClassifier(X_train, y_train, h=0.2 )
print((clf.predict(X_test) == y_test).astype('int8').sum()/test_size)

[[1.44181086 2.02190564 1.86544284 ... 1.43357101 1.66562277 1.87897278]
 [1.83207319 1.89872479 1.84249905 ... 1.55668295 1.71068218 1.8486015 ]
 [1.72315894 1.81364635 1.64048532 ... 1.00766588 1.70453881 1.75332725]
 ...
 [1.39863192 2.1106002  1.88111922 ... 1.51390296 1.67822573 1.88659983]
 [1.85218729 2.35507771 1.81561736 ... 1.7933546  1.87301414 1.71645102]
 [1.26768787 1.74927327 1.76605907 ... 1.67458843 1.61293027 1.66414497]]
[0. 0. 0. ... 0. 0. 0.]


ValueError: operands could not be broadcast together with shapes (4092,) (0,) 